import { createClient } from "@supabase/supabase-js";

export default async (req: Request) => {
  // Only allow POST requests for creating bookings
  if (req.method !== "POST") {
    return new Response(
      JSON.stringify({ error: "Method not allowed. Use POST." }),
      {
        status: 405,
        headers: {
          "Content-Type": "application/json",
          "Allow": "POST"
        }
      }
    );
  }

  try {
    const bodyText = await req.text();
    if (!bodyText) {
      return new Response(
        JSON.stringify({ error: "Empty request body" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    const { name, email, phone, selectedService, preferredDate, preferredTime, notes, ticketId } = JSON.parse(bodyText);

    if (!name || !email || !phone || !preferredDate || !preferredTime) {
      return new Response(
        JSON.stringify({ error: "Missing required fields" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    // Configure Supabase Client using environment variables or fallback credentials
    const supabaseUrl = process.env.SUPABASE_URL || "https://mjavuqwbespsnzlyeaks.supabase.co";
    const supabaseKey = process.env.SUPABASE_ANON_KEY || "sb_publishable_tDp7Hmnu4IQeVoLhgMn_Gw_7zPAQqpU";

    let synced = false;
    let syncErrorDetail: any = null;

    if (supabaseUrl && supabaseKey) {
      try {
        const supabase = createClient(supabaseUrl, supabaseKey);

        // Attempt to insert the booking details into supabase
        const { data, error } = await supabase
          .from("bookings")
          .insert([
            {
              ticket_id: ticketId,
              name,
              email,
              phone,
              selected_service: selectedService,
              preferred_date: preferredDate,
              preferred_time: preferredTime,
              notes: notes || ""
            }
          ])
          .select();

        if (error) {
          syncErrorDetail = error;
        } else {
          synced = true;
        }
      } catch (supabaseEx: any) {
        console.error("Supabase exception caught:", supabaseEx);
        syncErrorDetail = supabaseEx;
      }
    }

    // Prepare diagnostic SQL instructions if sync failed
    const troubleshootingSql = `
-- COPY AND PASTE THIS INTO YOUR SUPABASE SQL EDITOR:
-- 1. Create the 'bookings' table
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  selected_service TEXT NOT NULL,
  preferred_date DATE NOT NULL,
  preferred_time TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable insert/read operations bypass for testing or write custom policies
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Dynamic bypass policy (Insert access for everyone)
CREATE POLICY "Enable insert access for everyone" ON bookings FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Enable read access for everyone" ON bookings FOR SELECT TO anon USING (true);
    `.trim();

    if (!synced && syncErrorDetail) {
      console.warn("Supabase Sync Failed in Netlify Function. Fallback to offline workflow.");
      return new Response(
        JSON.stringify({
          success: true,
          synced: false,
          error: syncErrorDetail.message || "Supabase bookings table or permissions missing.",
          troubleshootingSql,
          ticketId,
        }),
        {
          status: 200,
          headers: { "Content-Type": "application/json" }
        }
      );
    }

    return new Response(
      JSON.stringify({ success: true, synced: true, ticketId }),
      {
        status: 200,
        headers: { "Content-Type": "application/json" }
      }
    );
  } catch (err: any) {
    console.error("Internal service error during intake:", err);
    return new Response(
      JSON.stringify({ error: err.message || "Internal server error" }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" }
      }
    );
  }
};
