import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware for parsing JSON
  app.use(express.json());

  // API endpoints FIRST
  app.post("/api/bookings", async (req, res) => {
    try {
      const { name, email, phone, selectedService, preferredDate, preferredTime, notes, ticketId } = req.body;

      if (!name || !email || !phone || !preferredDate || !preferredTime) {
        return res.status(400).json({ error: "Missing required fields" });
      }

      // Configure Supabase Client using the provided credentials
      // (Pre-populate with requested project keys, falling back to env vars if populated later)
      const supabaseUrl = process.env.SUPABASE_URL || "https://mjavuqwbespsnzlyeaks.supabase.co";
      const supabaseKey = process.env.SUPABASE_ANON_KEY || "sb_publishable_tDp7Hmnu4IQeVoLhgMn_Gw_7zPAQqpU";

      let synced = false;
      let syncErrorDetail = null;

      if (supabaseUrl && supabaseKey) {
        try {
          const supabase = createClient(supabaseUrl, supabaseKey);

          // Attempt to insert the booking details into supabase
          const { data, error } = await supabase
            .from("bookings")
            .insert([
              {
                ticket_id: ticketId,
                name,
                email,
                phone,
                selected_service: selectedService,
                preferred_date: preferredDate,
                preferred_time: preferredTime,
                notes: notes || ""
              }
            ])
            .select();

          if (error) {
            syncErrorDetail = error;
          } else {
            synced = true;
          }
        } catch (supabaseEx: any) {
          console.error("Supabase exception caught:", supabaseEx);
          syncErrorDetail = supabaseEx;
        }
      }

      // Prepare diagnostic SQL instructions if sync failed
      const troubleshootingSql = `
-- COPY AND PASTE THIS INTO YOUR SUPABASE SQL EDITOR:
-- 1. Create the 'bookings' table
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  selected_service TEXT NOT NULL,
  preferred_date DATE NOT NULL,
  preferred_time TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable insert/read operations bypass for testing or write custom policies
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Dynamic bypass policy (Insert access for everyone)
CREATE POLICY "Enable insert access for everyone" ON bookings FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Enable read access for everyone" ON bookings FOR SELECT TO anon USING (true);
      `.trim();

      if (!synced && syncErrorDetail) {
        console.warn("Supabase Sync Failed. Fallback to offline/in-memory flow.", syncErrorDetail);
        return res.json({
          success: true,
          synced: false,
          error: (syncErrorDetail as any).message || "Supabase bookings table or permissions missing.",
          troubleshootingSql,
          ticketId,
        });
      }

      return res.json({ success: true, synced: true, ticketId });
    } catch (err: any) {
      console.error("Internal service error during intake:", err);
      return res.status(500).json({ error: err.message || "Internal server error" });
    }
  });

  // Serve static assets or mount Vite dev middleware
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // Correct wildcard for Express 5: '*all' keyword instead of '*'
    app.get("*all", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
